file_map = {
    'JPEG': '.jpg',
    'PNG': '.png',
    'GIF': '.gif',
    'JPEG': '.jpeg',
    'PDF Files': '.pdf',
    'Text Files': '.txt',
    'Word Document': '.docx',
    'Excel Files': '.xlsx',
    'PPTX': '.pptx',
    'PPT': '.ppt',
    'MP3': '.mp3',
    'WAV': '.wav',
    'MP4': '.mp4',
    'AVI': '.avi',
    'Executable Files': '.exe',
    'Python Files': '.py',
    'C++ Files': '.cpp',
    'C Files': '.c',
    'Java Files': '.java',
    'HTML Files': '.html',
    'CSS Files': '.css',
    'JavaScript Files': '.js',
    'Zip Files': '.zip'
}

extension_map = {
    '.jpg': 'JPEG',
    '.png': 'PNG',
    '.gif': 'GIF',
    '.jpeg': 'JPEG',
    '.pdf': 'PDF Files',
    '.txt': 'Text Files',
    '.docx': 'Word Document',
    '.xlsx': 'Excel Files',
    '.pptx': 'PPTX',
    '.ppt': 'PPT',
    '.mp3': 'MP3',
    '.wav': 'WAV',
    '.mp4': 'MP4',
    '.avi': 'AVI',
    '.exe': 'Executable Files',
    '.py': 'Python Files',
    '.cpp': 'C++ Files',
    '.c': 'C Files',
    '.java': 'Java Files',
    '.html': 'HTML Files',
    '.css': 'CSS Files',
    '.js': 'JavaScript Files',
    '.zip': 'Zip Files'
}
